/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b6c4ff',
        'tertiary-container': '#004b1f',
        'inverse-on-surface': '#eef0ff',
        'on-primary-fixed-variant': '#264191',
        'secondary-container': '#86f2e4',
        'on-primary-fixed': '#00164e',
        'surface-container-low': '#f2f3ff',
        'on-tertiary-container': '#5ec074',
        'on-secondary-fixed-variant': '#005049',
        'surface-tint': '#4059aa',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#00210a',
        'on-surface-variant': '#444651',
        primary: '#00236f',
        'on-error': '#ffffff',
        'surface-dim': '#d2d9f4',
        'on-tertiary-fixed-variant': '#005323',
        'secondary-fixed-dim': '#6bd8cb',
        'surface-bright': '#faf8ff',
        'surface-variant': '#dae2fd',
        'on-background': '#131b2e',
        'surface-container-highest': '#dae2fd',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#79db8d',
        background: '#faf8ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#95f8a7',
        'surface-container': '#eaedff',
        'inverse-primary': '#b6c4ff',
        'primary-container': '#1e3a8a',
        'on-secondary-container': '#006f66',
        secondary: '#006a61',
        tertiary: '#003212',
        outline: '#757682',
        'surface-container-high': '#e2e7ff',
        'on-secondary-fixed': '#00201d',
        'inverse-surface': '#283044',
        'on-primary-container': '#90a8ff',
        'on-surface': '#131b2e',
        'primary-fixed': '#dce1ff',
        'outline-variant': '#c5c5d3',
        'secondary-fixed': '#89f5e7',
        'on-primary': '#ffffff',
        surface: '#faf8ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '1rem',
        'space-xl': '2rem',
        margin: '2rem',
      },
      fontFamily: {
        'label-md': ['Inter'],
        display: ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg': ['Inter'],
        'title-lg': ['Inter'],
        'title-md': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-sm': ['Inter'],
        'label-sm': ['Inter'],
        'headline-md': ['Inter'],
        'tabular-stat': ['Inter'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': [
          '30px',
          { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg-mobile': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' },
        ],
        'headline-sm': [
          '20px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.025em', fontWeight: '500' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' },
        ],
        'tabular-stat': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
