# Generated by Django 5.2.17 on 2026-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to True after the user confirms ownership of phone or email via OTP.'),
        ),
    ]
