# Generated by Django 5.2.17 on 2026-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('processing_fee_rate', models.DecimalField(decimal_places=2, default=0, help_text='Processing fee rate as a percentage (e.g., 2.5 for 2.5%, 2.00 = 2%)', max_digits=5)),
                ('repayment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_amount__gt', 0)), name='loanproduct_min_amount_positive'), models.CheckConstraint(condition=models.Q(('maximum_amount__gt', models.F('minimum_amount'))), name='loanproduct_max_amount_greater_than_minimum'), models.CheckConstraint(condition=models.Q(('processing_fee_rate__gte', 0), ('processing_fee_rate__lte', 100)), name='loanproduct_processing_fee_rate_between_0_and_100')],
            },
        ),
    ]
