# Generated by Django 5.2.17 on 2026-09-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProductTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_in_months', models.PositiveSmallIntegerField()),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='credit.loanproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('loan_product', 'term_in_months'), name='unique_loan_product_term'), models.CheckConstraint(condition=models.Q(('term_in_months__gt', 0)), name='loanproductterm_term_in_months_positive'), models.CheckConstraint(condition=models.Q(('annual_interest_rate__gte', 0), ('annual_interest_rate__lte', 100)), name='loanproductterm_annual_interest_rate_between_0_and_100')],
            },
        ),
    ]
