# Generated by Django 5.2.17 on 2026-09-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_loanproductterm'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('term_in_months', models.PositiveSmallIntegerField()),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('MORE_INFORMATION_REQUIRED', 'More Information Required'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('LOAN_CREATED', 'Loan Created')], db_index=True, default='DRAFT', max_length=32)),
                ('purpose', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='customers.customerprofile')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='credit.loanproduct')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='loanapplication_requested_amount_positive')],
            },
        ),
    ]
